### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by kmanasrah** [katokohaku/featureTweakR#1]
![screen shot 2018-04-15 at 10 01 53 am](https://user-images.githubusercontent.com/19980668/38780416-70e51464-40de-11e8-88de-7da62c3ecbba.png)

**Comment by katokohaku** [comment]
I am sorry that I do not notice your issue. I fixed the DISCRIPTION file. I think it can be installed now.

**Comment by kmanasrah** [comment]
It's working now, thanks!
